[client]
toolbarMode = "viewer" #Con esta configuración, la opción de "Deploy" no debería aparecer en la interfaz de tu aplicación.



[server]
maxUploadSize = 20
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501



[theme]

# The preset Streamlit theme that your custom theme inherits from.
# This can be one of the following: "light" or "dark".
base = "light"

# Primary accent color.
primaryColor = "#0077B5"  # Aldaba Red

# Background color of the app.
backgroundColor = "#FFFFFF"  # White

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#F8F8F8"  # Very light gray

# Color used for almost all text.
textColor = "#333333"  # Dark Gray

# Color used for all links.
linkColor = "#e33b1e"  # Match primary

# Background color used for code blocks.
codeBackgroundColor = "#F5F5F5"

# Font family
font = "sans-serif"

# The font family to use for code
codeFont = "monospace"

# The font family to use for headings.
headingFont = "sans-serif"

# Font faces (empty, as no custom fonts provided)
fontFaces = []

# Corner radius of UI elements
baseRadius = "0.25rem" # Sharper corners

# Border color
borderColor = "#E1E1E1"

# Whether to show a border around input widgets.
showWidgetBorder = true

# Base font size
baseFontSize = 16

# Show vertical sidebar separator
showSidebarBorder = true
