base_url = "http://rrhh.administracionapi.camsoft.com.do:8086"
#base_url = "https://srhapi.camsoft.com.do"
base_url = "http://rrhh.administracionapi.camsoft.com.do:8086"
#base_url = "https://srhapi.camsoft.com.do"
openai_api_key = "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"
