
##ENVIROMENT
#enviroment = "apis_qa"
enviroment = "apis"
#enviroment = "apis_dev"



[domain]
"jobsdev.triple.com.do" = "test.triple.com.do"
"jobs.triple.com.do" = "mallen.triple.com.do"
"empleos.mallen.triple.com.do" = "mallen.triple.com.do"
"empleos.dwn.triple.com.do" = "dwn.triple.com.do"
"empleos.aviat.triple.com.do" = "aviat.triple.com.do"
"empleos.electrom.triple.com.do" = "electrom.triple.com.do"
"empleos.fihogar.triple.com.do" = "fihogar.triple.com.do"
"empleos.plastico.triple.com.do" = "plastico.triple.com.do"
"empleos.gsm.triple.com.do" = "gsm.triple.com.do"
"empleos.soliden.triple.com.do" = "soliden.triple.com.do"
"empleos.sdr.triple.com.do" = "sdr.triple.com.do"
"empleos.fdd.triple.com.do" = "fdd.triple.com.do"
"empleos.caona.triple.com.do" = "caona.triple.com.do"
"empleos.bcotui.triple.com.do" = "bcotui.triple.com.do"
"empleos.bacricola.triple.com.do" = "bacricola.triple.com.do"
"empleos.demo.triple.com.do" = "demo.triple.com.do"


##### API PROD #############

[[apis]]
id = 0
name = "framework"
url = "https://api.framework.triple.com.do"

[[apis]]
id = 1
name = "administracion"
url = "https://api.administracion.triple.com.do"

[[apis]]
id = 2
name = "empleados"
url = "https://api.empleados.triple.com.do"

[[apis]]
id = 3
name = "nomina"
url = "https://api.nomina.triple.com.do"

[[apis]]
id = 4
name = "reclutamiento"
url = "https://api.reclutamiento.triple.com.do"

[[apis]]
id = 5
name = "reporteria"
url = "https://api.reporteria.triple.com.do"





##### API DEV #############


[[apis_dev]]
id = 0
name = "framework"
url = "http://rrhh.administracionapi.camsoft.com.do:8086/administracion"

[[apis_dev]]
id = 1
name = "administracion"
url = "http://rrhh.administracionapi.camsoft.com.do:8086/administracion"

[[apis_dev]]
id = 2
name = "empleados"
url = "http://rrhh.administracionapi.camsoft.com.do:8086/empleados"

[[apis_dev]]
id = 3
name = "nomina"
url = "http://rrhh.administracionapi.camsoft.com.do:8086/nomina"

[[apis_dev]]
id = 4
name = "reclutamiento"
url = "http://rrhh.administracionapi.camsoft.com.do:8086/reclutamiento"

[[apis_dev]]
id = 5
name = "reporteria"
url = "http://rrhh.administracionapi.camsoft.com.do:8086/reporteria"


##### API QA #############


[[apis_qa]]
id = 0
name = "framework"
url = "https://api.frameworkqa.triple.com.do"

[[apis_qa]]
id = 1
name = "administracion"
url = "https://api.administracionqa.triple.com.do"

[[apis_qa]]
id = 2
name = "empleados"
url = "https://api.empleadosqa.triple.com.do"

[[apis_qa]]
id = 3
name = "nomina"
url = "https://api.nominaqa.triple.com.do"

[[apis_qa]]
id = 4
name = "reclutamiento"
url = "https://api.reclutamientoqa.triple.com.do"

[[apis_qa]]
id = 5
name = "reporteria"
url = "https://api.reporteriaqa.triple.com.do"



##### API PRO OLD #############


[[apis_proo]]
id = 0
name = "framework"
url = "https://srhapi.camsoft.com.do/framework/fmk"

[[apis_proo]]
id = 1
name = "administracion"
url = "https://srhapi.camsoft.com.do/administracion"

[[apis_proo]]
id = 2
name = "empleados"
url = "https://srhapi.camsoft.com.do/empleados"

[[apis_proo]]
id = 3
name = "nomina"
url = "https://srhapi.camsoft.com.do/nomina"

[[apis_proo]]
id = 4
name = "reclutamiento"
url = "https://srhapi.camsoft.com.do/reclutamiento"

[[apis_proo]]
id = 5
name = "reporteria"
url = "https://srhapi.camsoft.com.do/reporteria"